[package]
name = "xp"
version = "0.1.0"
edition = "2024"
description = "A standard file format for resume / cv source data"
repository = "https://github.com/wazawoo/xp"
license = "MIT OR Apache-2.0"
keywords = ["cli", "json", "parser", "schema", "validation"]
categories = ["command-line-utilities", "parser-implementations", "text-processing"]

[package.metadata.release]
pre-release-hook = ["cargo", "run", "generate-schema"]
pre-release-commit-message = "chore: Generate JSON Schema"

[lints.clippy]
all = "warn"
cargo = "warn"
nursery = "warn"
pedantic = "warn"

[dependencies]
clap = { version = "4.5.55", features = ["derive"] }
env_logger = "0.11.11"
eserde = { version = "0.1.7", features = ["json"] }
log = "0.4.34"
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }

[dev-dependencies]
assert_cmd = "2.2.2"
